In [1]:
import sys
from pathlib import Path
sys.path.insert(0,str(Path().resolve().parent))
import pandas as pd

In [ ]:
#connection to the DB (main.py)
from src.utils.db import connect_to_db

#instanciating an engine
engine= connect_to_db()

parameters of DATABASE sucessfuly loaded
connection sucessful

In [ ]:
#loading table
#query(main.py)
query_f1_4 = """
    SELECT * FROM bronze.f1_4_air_releases_facilities
    WHERE "countryName"  = 'Belgium' AND "Pollutant"='Carbon dioxide (CO2)' AND "reportingYear" BETWEEN 2016 AND 2024
"""
#use of general function in main
f1_4_be_CO2= pd.read_sql(query_f1_4, con=engine)


print(f"F1_4 Belgique : {f1_4_be_CO2.shape}")

F1_4 Belgique : (597, 16)

In [64]:
f1_4_be_CO2

,PublicationDate,countryName,reportingYear,EPRTR_SectorCode,EPRTR_SectorName,EPRTRAnnexIMainActivity,FacilityInspireId,facilityName,city,Longitude,Latitude,addressConfidentialityReason,TargetRelease,Pollutant,Releases,confidentialityReason
0,2026/02/13,Belgium,2016,2.0,Production and processing of metals,2(b),BE.WA/012010000.FACILITY,INDUSTEEL BELGIUM,Marchienne-Au-Pont,4.411143,50.409920,None,AIR,Carbon dioxide (CO2),1.060000e+08,None
1,2026/02/13,Belgium,2017,1.0,Energy sector,1(c),BE.WA/112010000.FACILITY,ELECTRABEL - CENTRALE D'AMERCOEUR,Roux,4.395487,50.431004,None,AIR,Carbon dioxide (CO2),8.370000e+08,None
2,2026/02/13,Belgium,2024,4.0,Chemical industry,4(b)(i),https://data.ied_registry.omgeving.vlaanderen....,AIR LIQUIDE LARGE INDUSTRY,Antwerpen,4.287610,51.341620,None,AIR,Carbon dioxide (CO2),6.660000e+08,None
3,2026/02/13,Belgium,2021,1.0,Energy sector,1(c),BE.WA/119010000.FACILITY,LUMINUS - Centrale de Seraing,Seraing,5.490941,50.603073,None,AIR,Carbon dioxide (CO2),3.160000e+08,None
4,2026/02/13,Belgium,2021,3.0,Mineral industry,3(c)(i),BE.WA/028010000.FACILITY,HOLCIM Belgique - Usine d'OBOURG,Obourg,3.993890,50.472300,None,AIR,Carbon dioxide (CO2),1.070000e+09,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
592,2026/02/13,Belgium,2022,4.0,Chemical industry,4(a)(ii),https://data.ied_registry.omgeving.vlaanderen....,BASF ANTWERPEN,Antwerpen,4.272240,51.361750,None,AIR,Carbon dioxide (CO2),2.690000e+09,None
593,2026/02/13,Belgium,2023,1.0,Energy sector,1(c),BE.WA/112010000.FACILITY,ELECTRABEL - CENTRALE D'AMERCOEUR,Roux,4.395487,50.431004,None,AIR,Carbon dioxide (CO2),7.000000e+08,None
594,2026/02/13,Belgium,2020,1.0,Energy sector,1(c),BE.WA/187010000.FACILITY,2VALORISE AMEL,Amblève,6.085657,50.335556,None,AIR,Carbon dioxide (CO2),1.200000e+08,None
595,2026/02/13,Belgium,2016,5.0,Waste and wastewater management,5(b),BE.WA/003010000.FACILITY,IPALLE - Usine d'incinération,Thumaide,3.626551,50.549030,None,AIR,Carbon dioxide (CO2),4.400000e+08,None
596,2026/02/13,Belgium,2024,5.0,Waste and wastewater management,5(b),BE.WA/004010000.FACILITY,INTRADEL - UVELIA - Usine d'incinération,Herstal,5.643644,50.679726,None,AIR,Carbon dioxide (CO2),3.280000e+08,None

In [65]:
f1_4_be_CO2.columns

Index(['PublicationDate', 'countryName', 'reportingYear', 'EPRTR_SectorCode',
       'EPRTR_SectorName', 'EPRTRAnnexIMainActivity', 'FacilityInspireId',
       'facilityName', 'city', 'Longitude', 'Latitude',
       'addressConfidentialityReason', 'TargetRelease', 'Pollutant',
       'Releases', 'confidentialityReason'],
      dtype='str')

In [66]:
#nombre d'années manquantes
f1_4_be_CO2.isnull().sum()

PublicationDate                   0
countryName                       0
reportingYear                     0
EPRTR_SectorCode                  1
EPRTR_SectorName                  1
EPRTRAnnexIMainActivity           1
FacilityInspireId                 0
facilityName                      0
city                              7
Longitude                         0
Latitude                          0
addressConfidentialityReason    597
TargetRelease                     0
Pollutant                         0
Releases                          0
confidentialityReason           597
dtype: int64

In [73]:
#deleting unnecessary columns
col_to_keep=['reportingYear', 'EPRTR_SectorCode',
       'EPRTR_SectorName', 'FacilityInspireId',
       'facilityName', 'city', 'Longitude', 'Latitude',
       'Releases']
f1_4_be_CO2_mod=f1_4_be_CO2[col_to_keep].copy()

KeyError: "['reportingYear', 'EPRTR_SectorCode', 'EPRTR_SectorName', 'FacilityInspireId', 'facilityName', 'Longitude', 'Latitude', 'Releases'] not in index"

In [68]:
f1_4_be_CO2=f1_4_be_CO2.rename(str.lower, axis='columns').rename(columns={'releases':"emitted_co2_kg"})

In [69]:
f1_4_be_CO2

,reportingyear,eprtr_sectorcode,eprtr_sectorname,facilityinspireid,facilityname,city,longitude,latitude,emitted_co2_kg
0,2016,2.0,Production and processing of metals,BE.WA/012010000.FACILITY,INDUSTEEL BELGIUM,Marchienne-Au-Pont,4.411143,50.409920,1.060000e+08
1,2017,1.0,Energy sector,BE.WA/112010000.FACILITY,ELECTRABEL - CENTRALE D'AMERCOEUR,Roux,4.395487,50.431004,8.370000e+08
2,2024,4.0,Chemical industry,https://data.ied_registry.omgeving.vlaanderen....,AIR LIQUIDE LARGE INDUSTRY,Antwerpen,4.287610,51.341620,6.660000e+08
3,2021,1.0,Energy sector,BE.WA/119010000.FACILITY,LUMINUS - Centrale de Seraing,Seraing,5.490941,50.603073,3.160000e+08
4,2021,3.0,Mineral industry,BE.WA/028010000.FACILITY,HOLCIM Belgique - Usine d'OBOURG,Obourg,3.993890,50.472300,1.070000e+09
...,...,...,...,...,...,...,...,...,...
592,2022,4.0,Chemical industry,https://data.ied_registry.omgeving.vlaanderen....,BASF ANTWERPEN,Antwerpen,4.272240,51.361750,2.690000e+09
593,2023,1.0,Energy sector,BE.WA/112010000.FACILITY,ELECTRABEL - CENTRALE D'AMERCOEUR,Roux,4.395487,50.431004,7.000000e+08
594,2020,1.0,Energy sector,BE.WA/187010000.FACILITY,2VALORISE AMEL,Amblève,6.085657,50.335556,1.200000e+08
595,2016,5.0,Waste and wastewater management,BE.WA/003010000.FACILITY,IPALLE - Usine d'incinération,Thumaide,3.626551,50.549030,4.400000e+08
596,2024,5.0,Waste and wastewater management,BE.WA/004010000.FACILITY,INTRADEL - UVELIA - Usine d'incinération,Herstal,5.643644,50.679726,3.280000e+08

In [70]:
f1_4_be_CO2.isnull().sum()

reportingyear        0
eprtr_sectorcode     1
eprtr_sectorname     1
facilityinspireid    0
facilityname         0
city                 7
longitude            0
latitude             0
emitted_co2_kg       0
dtype: int64

In [71]:
f1_4_be_CO2=f1_4_be_CO2.fillna(value={"eprtr_sectorcode":'unknown','eprtr_sectorname':'unknown'})

In [72]:
f1_4_be_CO2.isnull().sum()

reportingyear        0
eprtr_sectorcode     0
eprtr_sectorname     0
facilityinspireid    0
facilityname         0
city                 7
longitude            0
latitude             0
emitted_co2_kg       0
dtype: int64

In [ ]:
f1_4_be_CO2.columns

In [89]:
from src.silver import transform_data_f1_4

f1_4be=transform_data_f1_4(f1_4_be_CO2,col_to_keep)[0]
metric=transform_data_f1_4(f1_4_be_CO2,col_to_keep)[1]

In [81]:
f1_4be

,reportingyear,eprtr_sectorcode,eprtr_sectorname,facilityinspireid,facilityname,city,longitude,latitude,emitted_co2_kg
0,2016,2.0,Production and processing of metals,BE.WA/012010000.FACILITY,INDUSTEEL BELGIUM,Marchienne-Au-Pont,4.411143,50.409920,1.060000e+08
1,2017,1.0,Energy sector,BE.WA/112010000.FACILITY,ELECTRABEL - CENTRALE D'AMERCOEUR,Roux,4.395487,50.431004,8.370000e+08
2,2024,4.0,Chemical industry,https://data.ied_registry.omgeving.vlaanderen....,AIR LIQUIDE LARGE INDUSTRY,Antwerpen,4.287610,51.341620,6.660000e+08
3,2021,1.0,Energy sector,BE.WA/119010000.FACILITY,LUMINUS - Centrale de Seraing,Seraing,5.490941,50.603073,3.160000e+08
4,2021,3.0,Mineral industry,BE.WA/028010000.FACILITY,HOLCIM Belgique - Usine d'OBOURG,Obourg,3.993890,50.472300,1.070000e+09
...,...,...,...,...,...,...,...,...,...
592,2022,4.0,Chemical industry,https://data.ied_registry.omgeving.vlaanderen....,BASF ANTWERPEN,Antwerpen,4.272240,51.361750,2.690000e+09
593,2020,1.0,Energy sector,BE.WA/187010000.FACILITY,2VALORISE AMEL,Amblève,6.085657,50.335556,1.200000e+08
594,2024,5.0,Waste and wastewater management,BE.WA/004010000.FACILITY,INTRADEL - UVELIA - Usine d'incinération,Herstal,5.643644,50.679726,3.280000e+08
595,2023,1.0,Energy sector,BE.WA/112010000.FACILITY,ELECTRABEL - CENTRALE D'AMERCOEUR,Roux,4.395487,50.431004,7.000000e+08
596,2016,5.0,Waste and wastewater management,BE.WA/003010000.FACILITY,IPALLE - Usine d'incinération,Thumaide,3.626551,50.549030,4.400000e+08

In [90]:
metric

{'table': 'silver_f1_4',
 'nb_null_in': np.int64(9),
 'nb_null_out': np.int64(7),
 'nb_col_out': 9}